export default{
    'es-cl':{
        'administrador':'Administrador',
        'gestor':'Gestor de cursos',
        'tutor':'Tutor',
        'supervisorTutor':'Supervisor Tutor',
        'editor':'Editor de cursos',
        'disenador':'Diseñador Gráfico',
        'desarrollador':'Desarrollador SW',
        'organizador':'Organizador',
        'gestionUsuarios':'Gestion de usuarios',      
        'about':'Quienes somos',
        'contacto':'Contacto',
        'cuestionarios':'Cuestionarios',
        'descripcion':'Descripción',      
        'evaluacion':'Evaluación',      
        'buzon':'Buzón',      
        'calificaciones':'Calificaciones',      
        'debates':'Debates',      
        'premios':'Premios',      
        'lista de control':'Lista de control',      
        'encuestas':'Encuestas',      
        'autoevaluacion':'Autoevaluación',      
        'agentes inteligentes':'Agentes Inteligentes', 
        'aulas virtuales':'Aulas virtuales'     
    },
}